### ISSUE TITLE
Capture requirements for JSONPath

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#100]
IETF has a group attempting to standardize JSON path, we should capture our use case and requirements (eg security...) and provide our input.

Edit: see https://datatracker.ietf.org/group/jsonpath/about/

**Comment by farshidtz** [comment]
Is it the same jsonpath group mentioned in https://github.com/w3c/wot-discovery/issues/56#issuecomment-715654792?

I think operators for ISO 8601 timestamp comparison are necessary. String operators are not very handy and often require complex regular expressions. 

Geospatial queries are nice to have, in case they are part of a TD (related to https://github.com/w3c/wot-discovery/issues/79).

OData examples from [OGC SensorThings](http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#54):
- Time comparison: `resultTime ge 2010-06-01T00:00:00Z`
- Geo distance: `geo.distance(Locations/location, geography’POINT(-122, 43)’) gt 1`

**Comment by mmccool** [comment]
Notes:
* Yes, as mentioned in [issue 56](https://github.com/w3c/wot-discovery/issues/56#issuecomment-715654792) so I added a link to the IETF group to the description

**Comment by mmccool** [comment]
Generally I have a concern that arbitrary JS should not be allowed in queries for security reasons (including DoS attacks by specifying pathologically expensive queries).  Instead there should be a specific set of comparison operators and query types supported.  I hope this aligns with what the IETF group is thinking.
