### ISSUE TITLE
Security bootstrapping during discovery

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-discovery#135]
**Problem**

There are a couple of sentences in the WoT Discovery spec which talk about only allowing authenticated entities to access TDs and TDDs.

> WoT Discovery has to allow authenticated and authorized entities (and only those entities) to find WoT Thing Descriptions satisfying a set of criteria, such as being near a certain location, or having certain semantics, or containing certain interactions.

 > The server SHOULD serve the requests after performing necessary authentication and authorization.

Currently security metadata is provided inside a Thing Description (for both things and directories), which causes a paradox:
1.  A consumer needs to parse the security medatadata in the Thing Description in order to know how to authenticate with the producer
2. A consumer can not access the security metadata in the Thing Description unless it is authenticated.

This is a problem with Thing Descriptions in general which is highlighted particularly well by the Directory Service API.

**Solution**

I propose a two step process by which a consumer can authenticate with the producer of a Thing Description (for both things and directories):
1. The first time a client fetches a Thing Description from the server, the server responds with a partial TD which contains only security metadata (and possibly the thing ID)
2. The client then performs the authentication steps necessary for (one of) the security scheme(s) described in the partial TD, before re-fetching the TD URL. Providing the authenticated user is authorised to access the TD, the server responds with the full TD.

First fetch:

```
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "securityDefinitions": {
        "basic_sc": {"scheme": "basic", "in":"header"}
    },
    "security": ["basic_sc"],
}
```

Second fetch, with basic authentication provided in header:

```
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "id": "urn:dev:ops:32473-WoTLamp-1234",
    "title": "MyLampThing",
    "securityDefinitions": {
        "basic_sc": {"scheme": "basic", "in":"header"}
    },
    "security": ["basic_sc"],
    "properties": {
        "status" : {
            "type": "string",
            "forms": [{"href": "https://mylamp.example.com/status"}]
        }
    },
    "actions": {
        "toggle" : {
            "forms": [{"href": "https://mylamp.example.com/toggle"}]
        }
    },
    "events":{
        "overheating":{
            "data": {"type": "string"},
            "forms": [{
                "href": "https://mylamp.example.com/oh",
                "subprotocol": "longpoll"
            }]
        }
    }
}
```

**Comment by farshidtz** [comment]
The TD of the directory can be (or should be) public. The security
definitions inside that TD are for accessing interactions. This is similar
to OpenAPI specs which are public and specify the endpoints and
authentication mechanisms to access those endpoints.

**Comment by benfrancis** [comment]
@farshidtz The problem with that approach is that a Thing Description isn't just an API description, it may contain private (meta)data which should not be made public.

This isn't just a problem for Thing Descriptions of a directory, it is a problem for all Thing Descriptions. Making all Thing Descriptions public risks revealing a great deal of sensitive information, for example in the context of the smart home. Providing public metadata about all the devices in a smart home, potentially including model numbers and even locations within the home, is like a shopping list for a burglar or cyber criminal and may reveal a great deal of information about the occupier of the building.

On the WebThings project we would like to expose a Thing Description for WebThings Gateway which exposes a directory but also exposes other functions like power cycling the gateway and putting its radios in pairing mode. Even the title and description of the gateway may reveal information the home owner may prefer to keep private.

**Comment by mmccool** [comment]
You raise a good point.  We probably need to define some special cases.

For directories, for example, we could say in advance they always use OAuth2 (for example).   Then once you have access to the directory, you can fetch the TDs it contains with that authentication, and there is no paradox.   (If we want more flexibility than that, we can do the same as what I propose below for self-description, which in summary is to limit security mechanisms to those in which the protocol itself provides enough information on what security is expected)

The tricky case is self-description.  We could define a default security mechanism just for accessing the TD on a Thing, then the TD itself could define other mechanisms for accessing other resources.  Unfortunately it's less clear in this case what the default should be.  If there was one clear default that worked in all cases we would not need the security data in the TDs.   However, we can cut down the options a lot since a lot of the weirder/more complicated options in there are to support brownfield devices or custom mechanisms thought up by CSPs or device manufacturers.   Brownfield devices would not be supporting self-description (they would be described "on the outside", by other agents).

Note that in some sense though the security metadata is redundant and is there mostly as documentation about what a developer can expect when they see a live Thing.  This is because all the protocols that I know of also indicate what security data is needed.  When you do a GET in HTTP on a resource protected by a password (for instance), the server will respond with a request for the password as part of the protocol.

However, we should at LEAST limit the options to those which the protocol provides the necessary information.  For example, HTTP password, OAuth2, and so forth.  We should disallow things like "body" and "apikey" since the protocol itself does not provide enough information about these.  I'm also thinking mostly HTTP for self-description, and maybe we could limit self-description to that protocol (although we might want to look at CoAP too, with a similar constraints; but I don't think we want to support self-description in MQTT, at least not in this round).

**Comment by mmccool** [comment]
So my above can be summarized as "limit security schemes for fetching the TD in self-description to those that can be specified in the protocol".   Specifically, this includes "basic", "digest", "bearer", "oauth", and actually "nosec".

For directories, one simple solution is to say the TD for the *directory* can always be accessed using "nosec".  However, other resources might require additional, more stringent security, but this will be specified in the TD returned by the directory service.

**Comment by farshidtz** [comment]
It may be my problem, but I always assumed the security definitions inside a TD are for the interaction affordances, not for the TD itself. If the TD needs to protected, then the security definitions must be defined elsewhere, perhaps a another TD (similar to discovery's Link Description type), telling how to interact with the private TD.

This is from the TD spec:
> Security configuration in the TD is mandatory. At least one security definition MUST be activated through the security member at the Thing level (i.e., in the TD root object). This configuration can be seen as the default security mechanism required **to interact with the Thing**.

We are now claiming that the security definitions set in the TD are also about accessing the TD itself. This really makes no sense. Is it specified anywhere?

**Comment by mmccool** [comment]
Nope, that's another problem, the security needed to fetch a TD is not specified in the TD itself.  So we can't extract just a security scheme from the TD, since it isn't given.  It's meta-metadata.

Anyhow, I added this to the agenda to discuss today...

**Comment by mmccool** [comment]
We COULD use the default (top-level) security definition as the security needed to access the TD.  That addresses one problem.

**Comment by benfrancis** [comment]
@mmccool wrote:
> For directories, for example, we could say in advance they always use OAuth2 (for example). Then once you have access to the directory, you can fetch the TDs it contains with that authentication, and there is no paradox.

Surely just knowing that a directory uses OAuth2 is not enough information on its own. How would a client find the token server and authorization server for example?

> The tricky case is self-description.

I'm not sure why it makes any difference whether a TD is serving its own Thing Description. Fundamentally in HTTP there's a client (WoT consumer) and a server (WoT producer). Either the Thing Description is public or it requires authentication. If it requires authentication then the client needs some way to know how to authenticate.


@farshidtz wrote:
> It may be my problem, but I always assumed the security definitions inside a TD are for the interaction affordances, not for the TD itself. If the TD needs to protected, then the security definitions must be defined elsewhere, perhaps another TD if we must (similar to discovery's Link Description type), telling how to interact with the private TD.

OK, that's similar to what I'm describing but with two separate TDs rather than two different views of the same TD depending on whether the client provides authentication credentials in the request.

> These are from the TD spec:
...
> We are now claiming that the security definitions set in the TD are also about accessing the TD itself. This really makes no sense. Is it specified anywhere?

OK, my reading of the draft discovery specification was that directories would be authenticated, but perhaps I misunderstood. I agree that for Thing Descriptions in general it is assumed that the TD is public, but that's the problem I'm trying to solve.

Let me provide a concrete example to help explain the issue we have with WebThings. Here is a hypothetical TD for the gateway (which acts as a directory, but also has other interaction affordances and semi-private metadata).

```json
{
  "@context": [
      "http://www.w3.org/ns/td",
      "https://w3c.github.io/wot-discovery/context/discovery-context.jsonld",
      "https://webthings.io/schemas"
  ],
  "@type": "DirectoryDescription",
  "title": "Smith Family WebThings Gateway",
  "version": {
    "instance": "42",
    "softwareVersion": "WebThings Gateway 1.0",
    "hardwareVersion": "WebThings Hub 1.0",
  },
  "securityDefinitions": {
      "oauth2_code": {
      "scheme": "oauth2",
      "flow": "code",
      "authorization": "https://auth.example.com/authorization",
      "token": "https://auth.example.com/token",
      "scopes": [
          "write",
          "read",
          "search"
      ]
    },
  "security": "oauth2_code",
  "properties": {
    "things": {...}
  },
  "actions": {
    "createThing": {...},
    "updateThing": {...},
    "deleteThing": {...},
    "reboot": {...},
    "shutDown": {...},
    "pair": {...},
    "unpair": {...}
  },
  "events": {
    "thingCreated": {...},
    "thingUpdated": {...},
    "thingDeleted": {...}
  }
}
```

In the case of the gateway, the whole API is authenticated using JSON Web Tokens in the HTTP Authorization header (which are issued to the user once they enter a username and password) and supports OAuth2 for third party applications to authenticate with the API. The same token is used for both the REST API and WebSocket API and is valid for all devices the authenticated user has access to (accessing the Thing Descriptions of all the devices requires authentication using the same token).

We would ideally rather this top level Thing Description not be public because it may contain metadata which would reveal information about the household and the smart home hub they are using. Therefore it would be authenticated using the same JWT.

In order to authenticate with the gateway's web server, my understanding is that an API client needs to know the authorization and token server, but that information is locked up inside this top level TD.

@farshidtz So in order to make this top level TD authenticated, are you saying that there would need to be another TD which acts as a Link Description which only provides security metadata and a link to the gateway's TD?

Separately the WebThings Framework provides WoT servers (producers) for individual devices which are broadcast using mDNS. Are you suggesting that if we didn't want their full TDs to be public that each device would need two TDs: A Link Description with just security metadata and a link to a separate Thing Description with the full metadata?

**Comment by mjkoster** [comment]
Given that we consider it to be a bootstrapping issue for clients to get the authentication instructions,  it sounds like the expected case is that a client will not know how to authenticate, and need to get some sort of instructions. If so, we may consider a normal TD fetch where there is a special TD that contains the authentication instructions, and the client is aware of this up front. I think we called this Ben's proposal. Why would it be better to use an error signal and require the client to have another method to obtain the authentication instructions, if it is the expected behavior? The introduction phase could offer this standalone authentication TD, not as an alias to the TD the client really wants, but a separate control document.

**Comment by relu91** [comment]
I think this might be related to the fact that we don't really have a standard way to retrieve a TD. I was wondering if Discovery would try to have a description of how to that. 

Describing error types and standard parameters could be the first step forward. Since if we're going to stick with the current approach that the "real" discovery should always start from an URL we need additional information to _really_ retrieve it.

 See also #90.

**Comment by benfrancis** [comment]
@mjkoster wrote:
> Given that we consider it to be a bootstrapping issue for clients to get the authentication instructions, it sounds like the expected case is that a client will not know how to authenticate, and need to get some sort of instructions. If so, we may consider a normal TD fetch where there is a special TD that contains the authentication instructions, and the client is aware of this up front. I think we called this Ben's proposal. Why would it be better to use an error signal and require the client to have another method to obtain the authentication instructions, if it is the expected behavior?

I don't really mind whether the initial fetch responds with a success or error response, but `401 Unauthorized` (which [really means](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses) "unauthenticated") might be a good fit here as compared to `403 Forbidden`.

[401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) is "similar to 403, but in this case, authentication is possible."

> The introduction phase could offer this standalone authentication TD, not as an alias to the TD the client really wants, but a separate control document.

This is kind of what @farshidtz was suggesting with a Link Description, but it means that every device needs to serve two different resources instead of one, which really doesn't seem necessary when there's an obvious alternative.

**Comment by benfrancis** [comment]
Has there been any progress on this?

1. How should a discovered Web Thing or Directory respond if a Consumer tries to fetch a TD or TDD but isn't authenticated to access it?
2. What should a Consumer do if its request to access to a TD or TDD receives such a response (e.g. 401 Unauthorized)? 

One solution might be:

1. The Producer responds with a 401 Unauthorized response, with authentication instructions in a [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) header
2. The Consumer then attempts to authenticate using the specified mechanism before re-fetching the TD/TDD

That's obviously HTTP specific, but that would seem appropriate at least for the HTTP binding provided for the Directory Service API.

**Comment by farshidtz** [comment]
> One solution might be:
> 
> 1. The Producer responds with a `401 Unauthorized` response, with authentication instructions in a [`WWW-Authenticate`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) header
> 2. The Consumer then attempts to authenticate using the specified mechanism before re-fetching the TD/TDD
> 

Recommending that for all HTTP interactions is a good idea. 

This is actually the mandatory approach for OAuth2: https://datatracker.ietf.org/doc/html/rfc6750#section-3

**Comment by benfrancis** [comment]
I've added the "Resolve prior to WD update" label here because it seems to me that the discovery process will be useless in many cases without this feature. It's certainly a blocker for implementing WoT Discovery for WebThings Gateway where all Thing Descriptions require authentication for privacy reasons.

Please feel free to remove the label if it's inappropriate.

**Comment by benfrancis** [comment]
Since https://github.com/w3c/wot-discovery/pull/311, the latest draft of the specification says that a `401` response is "often accompanied by a `WWW-Authenticate` header", but it doesn't define what values can be expected by a client. Without further specification, that presumably implies that servers may use any present and future authentication scheme from the IANA [Hypertext Transfer Protocol (HTTP) Authentication Scheme Registry](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml), and therefore clients must support all present and future schemes.

If the goal is for any client to be able to consume any directory, then I suggest the specification probably needs to be more prescriptive and say that a `401` response must always contains a `WWW-Authenticate` header, and to constrain the values of that header to a finite list of authentication schemes.

That way it's clear what authentication schemes a directory server may use, and therefore which authentication schemes a client must support in order to access any directory.

This also assumes that the `WWW-Authenticate` header alone provides enough information for a client to authenticate with a directory without the need for any additional out-of-band information (except that provided as part of the authentication process like a user filling out a login form). Hopefully that is the case, but I don't know enough about each of the authentication schemes to be sure.

**Comment by mmccool** [comment]
I also agree with Ben that we should REQUIRE the response to have a WWW-Authenticate header, as well as limiting the allowable schemes to the ones mentioned.

**Comment by mmccool** [comment]
PR created: https://github.com/w3c/wot-discovery/pull/313.  Please review.  I will keep it in draft status until I see reviews from people who have actively contributed to this issue.
