### ISSUE TITLE
Method to query content length before exploration

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-discovery#146]
The spec should include mechanisms to know the response size before retrieving TD(s) from a device or directory.

For HTTP, this should be as simple as making a [HEAD request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) to get the Content-Length. This is applicable to:

- Self-describing devices. Small consumers should know if they can accommodate the whole TD or should instead make a selection query #132 
- Retrieving a single TD from a directory. Same as above.
- Retrieving multiple or all TDs. Consumers should be able to know if the response is too large for them to process and if they should adjust their query. #145

**Comment by mmccool** [comment]
- We need to add a "HEAD" request to all endpoints 
- Not clear how to add this to the TD; we could do it outside the TD spec (e.g. add an assertion that HEAD should be supported for a certain set of interactions under HTTP, and to include Content-Length)
- How does this interact with pagination?  A: should be exactly what we would returned for a GET; just the headers, just no body
- Should raise an issue to consider how to include this in the TD spec

**Comment by mmccool** [comment]
@farshidtz will add a PR
