### ISSUE TITLE
Discovery context and namespace under w3.org/ns

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-discovery#148]
The discovery spec currently references the context and ontology using the draft URL. 

What is the process of hosting [these](https://github.com/w3c/wot-discovery/tree/main/context) under w3.org/ns/wot-discovery?

I found the following, already defined by the WoT WG:
- https://www.w3.org/ns/td
- https://www.w3.org/ns/wot-security
- https://www.w3.org/ns/json-schema

Once this is done, we can update the referenced context URLs and the namespace for type URIs. Also related to #54.

**Comment by farshidtz** [comment]
@knimura any idea? There are many "draft" URLs in the spec and ontology and is is getting out of hand.

**Comment by mmccool** [comment]
@mmccool to create a PR for option 2.

**Comment by mmccool** [comment]
I seems I was supposed to do a PR to implement option 2.  Will at least check it has been done, in time for the CR transition.
But at this point, we can use a combination of 1 and 3: 
- Normatively propose a URL as in 1, that will go into CR transition
- Add an ed note that says that for the purposes of testing, implementations may use the github URL up until PR.

@mmccool - need a PR, prior to CR transition.

**Comment by mmccool** [comment]
Ed note is there, but we still need to resolve by PR.  Changing label to "Resolve by PR".

**Comment by mmccool** [comment]
Think this is all sorted out now, closing.
