### ISSUE TITLE
EnrichedThing as a class?

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [w3c/wot-discovery#169]
After some discussions with @farshidtz, we came up with a new model for the discovery ontology. Specifically for how to modify the current RegistrationInformation class into a new one named EnhancedThing. The benefits from a syntactically point of view is that all the registration terms will appear in the root of the document, instead, from an ontological point of view the new class is more aligned with what the spec states in the text.

The current ontology is the following:
![](https://raw.githubusercontent.com/w3c/wot-discovery/main/images/directory-td-class-diagram.svg)
A sample payload that is compliant with this model could be:
`````
{
    "@context": [
        "http://www.w3.org/ns/td",
        "https://w3c.github.io/wot-discovery/context/discovery-context.jsonld"
    ],
    "@type": "Thing",   
    "id": "urn:example:expirable-td",
    "security": "basic_sc",
    "securityDefinitions": {
        "basic_sc": {
            "scheme": "basic"
        }
    },
    "registration": {
        "created": "2021-05-10T16:00:00Z",
        "modified": "2021-05-10T17:00:00Z",
        "expires": "2021-05-10T18:00:00Z",
        "ttl": 3600,
        "retrieved": "2021-05-10T17:35:00Z"
    },
    "title": "Expirable TD"
}
`````
Instead, the new model would be (there is a typo, EnhancedThing would be EnrichedThing):
![](http://www.plantuml.com/plantuml/svg/ZP7DIiH048Jl_HHDJdhO5yX15emtlUqBJD8LqpW_otG7LzHtbqqGDxY8SngglfgQflVceVgS8aqgu8JKeneDCPXnuz8U9itF3VqeqZxaAUG1ibhyJimsJ4YXbU2uhmWEuPPF9elYch1bdeheg7z0E1srmdxxvtxt-6sKkO-WJxAfl5xzN72lsiyE8yh5mH6ZSnalPcDYNcxSmOQgHzUI-URGtHAoy3b5ordUVzJySi4rlDjzt5shNl5EAmOlzUt_cQssmfjLq1vPvXI_0000)

The previous payload would look like the following:
`````
{
    "@context": [
        "http://www.w3.org/ns/td",
        "https://w3c.github.io/wot-discovery/context/discovery-context.jsonld"
    ],
    "@type": "EnrichedThing",   
    "id": "urn:example:expirable-td",
    "security": "basic_sc",
    "securityDefinitions": {
        "basic_sc": {
            "scheme": "basic"
        }
    },
    "registrationCreated": "2021-05-10T16:00:00Z",
    "registrationModified": "2021-05-10T17:00:00Z",
    "expires": "2021-05-10T18:00:00Z",
    "ttl": 3600,
    "title": "Expirable TD"
}
`````

What do you think? shall we move towards this new model?

**Comment by mmccool** [comment]
- Should also work with ThingModel.  What if I want an EnrichedThingModel?   Note: not a short-term problem since TDD only store TDs, not TMs.
- Prefixes are more explicit, easy to see what should be removed to get back to the original TDs.  But prefixes can be hidden in context files, aliased, etc. anyway so not really safe to depend on them.
- In some cases (e.g. ttl) Thing needs to provide information that is part of the enriched data namespace, not core TD vocabulary.  Is this easier to deal with (eg. for validation) for extensions vs. subclass? (discussion: non-problem).

**Comment by mmccool** [comment]
I think the model is fine, but would like to see prefixes; that would address most of my concerns.

**Comment by mmccool** [comment]
- @ashimura need to consider how this interacts with extension mechanism
- Note that can't just search for fixed prefix, need to look at URLs
- New directory extension not a privacy risk; can be built-in, no need to fetch

**Comment by mmccool** [comment]
Resolved; not going to add this class.
