### ISSUE TITLE
Identifying what information is conveyed in the TD and what is conveyed in the text

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-discovery#183]
In the call of 24.05.2021, it was pointed out that there are some specifications that are conveyed by the TD and some that are conveyed by the specification. I looked at it after the meeting and I fail to see big differences. What I see so far are:

### In the spec but not in the TD
- In general: 
  -  401 and 403 responses
  - actions in the TD are said to be properties in the spec, i.e. "This operation is specified as updatePartialTD property in Example 3. "
- Creation: 
  - Sending TD with id or without one is a different process. The TD has two forms but how can a Consumer know which one to pick based on having an id. Even then, how to know that that id is that id?
  - expiry and TTL. How does a client set this?
- Retrieval: looks good
- Update: looks good
- Deletion: looks good
- Listing: 
  - `limit` can be negative in the TD
  - The text says that the next Link header is sent only if there are more than can be sent. The TD is read as if Link header is always sent.
  - What to do with the Link header: I am not super sure. Do we say anywhere that `htv:fieldName` values should be understood by the implementation and followed accordingly. In other words, if a non TDD Thing sends a response with Link header, should a Consumer follow it?
  - The whole part about canonical Link header?
  - 501 response
  - Good luck for someone who only reads the TD to understand listing. It is clearly underspecified in the TD and I don't think that it is possible. This is a subprotocol for me. It is not a single request-response but doing a set of them in specific ways.
- Search
  - JSONPath: Looks good but I think that a format for the string in the TD would help
  - XPath: Same regarding format.
  - SPARQL: The POST method way does not have any input not uriVariables, so how is query sent?

  - How the path looks like (with an id)

### In the TD but not in the spec
- In general:
  - How the path looks like (with an id)
  - `application/problem+json` contentType
  - use of `scopes`

### Notes
- The reason for the issue is that this difference needs to be documented. Why?:
  - A newcomer cannot cross-check two types of specifications and understand the differences. Better to communicate it in advance
  - Difficult to maintain. When the API needs to be updated for a newer version of the spec, and if this update is not by the same people, there can be parts that are not updated.

- From my analysis, there is definitely more information in the spec than in the TD. Thus, from my analysis, the claim in the meeting of 24.05 was not correct. One does need to read the spec and not everything is put in the TD.

**Comment by farshidtz** [comment]
Thanks for the comparison. I also want to point out that some things are not explicitly mentioned in the spec but instead referenced, such as for Problem Details, SSE, SPARQL.

> Thus, from my analysis, the claim in the meeting of 24.05 was not correct. One does need to read the spec and not everything is put in the TD.

I don't remember this. To me, it is clear that TD and spec complement each other. TD, for sure, doesn't cover all the details.

This is written before introducing the TD:
> Below is a generic Thing Description for the Directory HTTP API with OAuth2 security. The Thing Description alone should not be considered as the full specification to implement or interact with a directory. Additional details for every interaction are described in human-readable form in the subsequent sections.

**Comment by egekorkan** [comment]
Ok that might be my bad. In any case, I do find it annoying for a newcomer that they need to read to documents. I think that the TD does not contain too much information that cannot be put in the text so why not moving everything into text and moving the TD to the appendices?

**Comment by farshidtz** [comment]
> I think that the TD does not contain too much information that cannot be put in the text so why not moving everything into text and moving the TD to the appendices?

Making the text self-contained is a good idea. I guess that would be an editorial change which we can work on even after the CR.

I also think that the huge TD placed in the middle of the text is adding confusion and gaining unnecessary attention. Moreover, it is making the spec less readable. Moving it to a dedicated section at the end (normative or informative) is a good idea.

**Comment by mmccool** [comment]
Resolution: main points have been addressed.   There might be a few small things left over, e.g. we might want to declare scopes in all our forms even in our TDD's TM even if OAuth is not defined, to make them more consistent, but this *specific* topic can be covered in a more specific issue.  In general, we should aim for one-problem, one-issue, and any additional points not yet addressed should each get their own issue.

**Comment by mmccool** [comment]
Actually closing now.
