### ISSUE TITLE
Update change log for WD2

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#189]
The change log needs to be updated before we can publish WD2.

A diff between the FPWD and the WD2 candidate is available at:
  https://w3c.github.io/wot-discovery/publication/2-wd/diff.html
The previous version is at
  https://www.w3.org/TR/2020/WD-wot-discovery-20201124/

**Comment by mmccool** [comment]
Could not get to this today, will do it first thing tomorrow.  @ashimura I assume that I should do a PR against main, and you will copy over the content to the release?

**Comment by ashimura** [comment]
Thanks, @mmccool !
Yes, I'll work on the publication draft based on your updates :)

**Comment by mmccool** [comment]
Scanning the diff, here are the changes I see:
- Update name of directory service to "Thing Description Directory" with acronym TDD, to avoid confusion with the acronym for Thing Description.
- Elaboration of complete API for registration of a Thing Description with a Thing Description Directory, including support for creation, update, retrieval, deletion, and listing.
- Add recommendation that TDs be validated before storage in a directory.
- Addition of Security and Privacy Considerations regarding Denial of Service and Location Tracking.
- Addition of IANA Considerations regarding CoRE Resource Types.
- Definition of Enriched TD for embedded metadata in TDs returned by a TDD.
- Updates to descriptions to avoid unnecessary dependence on HTTP (in the future, other protocols may be supported)
- Use of "resource type" instead of "endpoint type" when describing entry in CoRE RD.
- Addition of ontology for TDDs that include the type "DirectoryDescription" identifying TDs of directories and a type "LinkDescription" to identify a TD that is just a link to another TD (useful for referring to remote directories in order to support federation).
- Add section for self-description exploration mechanism.  This supports the case where a Thing hosts its own TD.
- Addition of diagram showing the directory information model.
- Removal of reference to Issue 16, citing CRUD interfaces.  Replaced with CRUDL (CRUD + Listing) interface requirement.
- MAY assertion added to explicitly permit implementation of SPARQL federation, and a requirement that if implemented, it needs to follow the SPARQL 1.1 specification.
- Updates to references: more recent version of CoRE RD, DID Core, Eventsource, JSON-LD, and JSON Path specifications.  Use of datatracker to reference IETF RFCs.  Addition of normative references to RFC7396 and RFC7540. 

I will make a PR with the above.

Notes:
* I noticed the first sentence in in the introductions (e.g. 5.2, 5.3...) converted a "MAY" (RFC2119 assertion) to a "may" (not an RFC2119 assertion).  Based on the text I think this is a mistake and these should be turned back into assertions.
* There seems to be a self-reference to wot-discovery, which is weird.   We can leave it for now, but...

**Comment by mmccool** [comment]
I'll also create issues for the two other things noted...

**Comment by mmccool** [comment]
Farshid, do you agree that we can merge this PR and proceed with publication?

**Comment by farshidtz** [comment]
Yes, assuming that this change log is meant to be inside WD2 to compare it against WD1. The current working draft of course includes more changes.

**Comment by mmccool** [comment]
Right, this is just for WD2 relative to WD1 (aka the FPWD).  It would be good to get started on another change log for the latest changes, however.

**Comment by ashimura** [comment]
Thanks a lot!
I've applied all the changes to the [Publication draft](https://w3c.github.io/wot-discovery/publication/2-wd/).
