### ISSUE TITLE
Assertions removed by mistake for Introductions?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#193]
I noticed the first sentence in in the introductions (e.g. 5.2, 5.3...) converted a "MAY" (RFC2119 assertion) to a "may" (not an RFC2119 assertion). Based on the text I think this is a mistake and these should be turned back into assertions.  Was this intentional, and if so, what was the rationale?

**Comment by k-toumura** [comment]
I thought it would be enough to have only the names used in each mechanism (`wot-thing-description`, `_wot`,  `wot.thing` etc.) as assertions, so I eliminated the assertions at the beginning of each section.
If this is not sufficient as assertions, I agree with putting the first sentence back in as an assertion.

Also, since the name of Well-Known URI is not in the assertion in section 5.2, it may be need to be modified as follows:
> If Thing or Thing Description Directory registers its own Thing or Directory Description using Well-Known URI, they MUST use the following path: `/.well-known/wot-thing-description`.

**Comment by mmccool** [comment]
Let's discuss in the next call.  I'm also wondering if the long URLs used will be a problem in some contexts...

**Comment by k-toumura** [comment]
For a URI naming, [the list of IANA registered URI](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) is a good reference.

We can use simple name such as `wot` for Well-known URI.
However, [RFC8615](https://datatracker.ietf.org/doc/html/rfc8615#section-3) says the following, so maybe a more accurate name would be better...
> Registered names for a specific application SHOULD be correspondingly
   precise; "squatting" on generic terms is not encouraged.  For
   example, if the Example application wants a well-known location for
   metadata, an appropriate registered name might be "example-metadata"
   or even "example.com-metadata", not "metadata".

**Comment by mmccool** [comment]
right, I was not suggesting getting rid of the "wot" part, but maybe "wot-td" would be better.   I'm just wondering if really long URLs might cause problems with protocols over UDP, etc. with limited packet sizes.

**Comment by mmccool** [comment]
So, we've factored out the URI naming to a different issue.  The remaining point is whether we need an assertion here.   

Suggested resolution:
1. All subsections in 5.1 should use MAY in their first sentence (and would be assertions, since these are permitted mechanisms).
2. Direct needs to be updated so its first sentence is "Any mechanism that results in a single URL MAY be used."  Right now it's not a sentence, let alone one with "may".

See also issue https://github.com/w3c/wot-discovery/issues/200 - we also need to make clear, in the intro itself, that NO *particular* introduction mechanism is mandatory.  Or rather, anything that gives you a URL is fine (and "Direct" covers any such mechanism).
