### ISSUE TITLE
Exploration Mechanisms

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-discovery#202]
Chapter 6 is mainly concerned with two exploration mechanisms, self-description and directory. I think a typical mechanism is also indirect self-description through a proxy-based instance. E.g. a uCs that are unable to expose a TD due to memory limitations TD must be downloaded/fetched from the edge hosting the TD via file servers or the developer has collected the TD locally (e.g., downloaded from the manufacturer's website).

**Comment by mmccool** [comment]
I think this has been resolved by the addition of "TD Servers" which can be any web resource providing a TD (does not have to be on the device, or in a directory, but both are possible implementations).  Will mark this as "Propose closing" although during final review we should check that there is not any text that disallows proxies, etc.

However, note that a proxy may have to modify TDs as well, e.g. adding proxy security information or changing URLs.  So issue #257 may also be relevant.  Disallowing changes to TDs may break proxies, if a proxy is re-exposing TDs.  There is nothing saying a servient can't tweak TDs in such a way, and it's needed for other use cases (e.g. adding TLS termination, access controls, etc).
