### ISSUE TITLE
Sharing TDs via other means

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#212]
As discussed in the June 2021 F2F, should we discuss sharing of TDs by other means, e.g. file transfers, USB sticks, etc.
IMO this should probably be permitted but we should include a recommendation that signatures "SHOULD" be used in this case to validate authenticity.   Let's wait until we see if signatures are included in the TD spec... should be soon, I hope

**Comment by farshidtz** [comment]
Similar to #202

**Comment by mmccool** [comment]
OK, no signatures.  Spec does allow distribution of TDs as a regular web resource via WoT Discovery, but since WoT Discovery is optional sharing of TDs by "other means" is implicitly supported.  So my feeling is that we don't have to do anything else here and can close this issue.
