### ISSUE TITLE
Move common terminology to the Architecture spec

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-discovery#240]
There are some terminology entries that are common and should be moved to the architecture terminology section.
Examples include "Anonymous TD", Thing Description Directory, Partial TD, Discovery

**Comment by k-toumura** [comment]
related issue: w3c/wot-architecture#613

**Comment by mmccool** [comment]
Note that there are NO definitions in Discovery any more, the PR above moves *everything* to Architecture (well, it deletes them in Discovery, another PR to update Architecture is pending)
