### ISSUE TITLE
Disallow SPARQL UPDATE operations

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-discovery#245]
The spec indicates that `UPDATE` is out of the scope of the SPARQL Seach API: https://github.com/w3c/wot-discovery/blob/40267a23442a44beca4724f4d7495eeba2e9deed/index.html#L1834

In the discovery call today, it was proposed that this statement be changed to explicitly disallow this operation. An appropriate status code should be set in response to such query, perhaps 403 Forbidden.

**Comment by AndreaCimminoArriaga** [comment]
I agree, the UPDATE query would allow registering TDs (or modifying existing ones) bypassing the endpoints for such purpose.

**Comment by mmccool** [comment]
The SPARQL system has different endpoints for UPDATE, so we could simply not support the UPDATE endpoint.  @AndreaCimminoArriaga will investigate.

**Comment by wiresio** [comment]
In Apache Jena an update on the /query endpoint results in http 400 (bad request)

**Comment by AndreaCimminoArriaga** [comment]
I have created a PR for this issue, but I have a parallel question. Shall we add examples of JsonPath, Xpath and SPARQL queries on the spec?

**Comment by farshidtz** [comment]
I propose we close this issue since the PR has been merged.

> I have created a PR for this issue, but I have a parallel question. Shall we add examples of JsonPath, Xpath and SPARQL queries on the spec?

We have separate issues for this:
- #81 
- #141
