### ISSUE TITLE
Change event affordance names

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-discovery#258]
To avoid confusion, I propose changing the names of the event affordances in the Directory Service API to match the URLs proposed in #251. 

- `thingCreation` -> `thingCreated`
- `thingUpdate` -> `thingUpdated`
- `thingDeletion` -> `thingDeleted`

See #251 for further discussion.

**Comment by farshidtz** [comment]
I agree that this causes confusion. I've added a commit to the existing refactoring PR to also take care of this.
