### ISSUE TITLE
@context for Directory is not working

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [w3c/wot-discovery#262]
The current [@context](https://w3c.github.io/wot-discovery/context/discovery-context.jsonld) of the directory is not working due to the following statements:

````json
  "total": "discovery:contains",
    "members": [
      "td:Thing"
    ],
    "@id": "discovery:thisThingCollection",
    "next": "discovery:nextThingCollection",
````

If removed these lines it works again. @wiresio I think these statements where introduced in your last commit. I created a PR fixing the "total" and "next" . Nevertheless some errors persist:

* The first one is related to  "@id": "discovery:thisThingCollection" which specifies that whatever uses this context has automatically the type 'discovery:thisThingCollection' which is not true. I think the best is  just removing this line (everything will still work by just adding in the TD the "@type" with `discovery:thisThingCollection` as it is done for the rest of the types in this context).

* On the other hand, related to  the key "members" I get this error. 
````
jsonld.SyntaxError: Invalid JSON-LD syntax; @context term values must be strings or objects.
````
Please could you review this last error to include correctly this key.

I create a PR #261 with the properties total and next, and without the "@id" and "members" so it can be merged and have the context working again in the meanwhile the previous issues are fixed

**Comment by AndreaCimminoArriaga** [comment]
Also, when we solve this issue the ontology file should be updated

**Comment by mmccool** [comment]
The "members" element still needs to be fixed. Christian Glomb (@wiresio) will address.

**Comment by wiresio** [comment]
@AndreaCimminoArriaga - do you think that this fix is sufficient?

https://tinyurl.com/y7xspzox

**Comment by AndreaCimminoArriaga** [comment]
@Glomb, Christian ***@***.***> Yes, I tested it and it
works perfectly. I will modify the ontology after the PR is merged with the
new context.
Best,
Andrea C.

**Comment by wiresio** [comment]
Thanks @AndreaCimminoArriaga for testing!

Please allow a bit more time and then I'll prepare a PR for this. Cannot join the JF today but want to have something ready for next week.

**Comment by mmccool** [comment]
Fixed?

**Comment by wiresio** [comment]
Yes, fixed.
