### ISSUE TITLE
Reconsider/Refine Self-Discovery Security Assertions

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#265]
Should revisit use of SHOULD in <strike>section 6.1</strike> section 8.3, "Self-Discovery on LANs".  Should reword also to deal with case of proxy, perhaps saying "exposure of public API".  Note that there are (perhaps) use cases for self-description without a need for authentication, e.g. public services.  The "MUST" part would really only apply to privately-owned devices where exposing metadata has privacy implications.

**Comment by farshidtz** [comment]
See also: https://github.com/w3c/wot-discovery/issues/139

**Comment by mmccool** [comment]
This section has been pretty much completely reworked, so I think we can close this issue, but reopen it if there are additional issues with the new text.
