### ISSUE TITLE
Redundant fields from TDs introduced by TDD

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [w3c/wot-discovery#270]
In the TDD we have defined a context that has several registration fields, I have notice that now the TD spec introduces fields such as `created` or `modified`. Shall we revisit the fields added in the TDD context to avoid redundancy?

**Comment by farshidtz** [comment]
The created and modified fields were in the TD long before discovery spec was written. If you remember, we spent a lot of time designing the ontology to avoid conflicts. Those fields were mentioned in our early designs: https://github.com/w3c/wot-discovery/issues/98#issuecomment-739245896

To know why we didn't use those fields in discovery; see https://github.com/w3c/wot-discovery/issues/18#issuecomment-623501523

**Comment by AndreaCimminoArriaga** [comment]
Ok, my concerns were due to the update in their ontology in case we also should revisit ours. I will close this issue then.
