### ISSUE TITLE
Add a Directory to a Directory

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-discovery#271]
**User story:** As a user I want to add a directory of things to another directory so that I can manage multiple directories from a single larger directory.

**Use case:** A cloud service used for monitoring multiple buildings, each with their own Web of Things gateway. The user could add a whole building full of devices to the cloud service using the URL of its gateway's Directory Description.

Currently in order to achieve this each Thing Description from the gateway would have to be added to the cloud directory individually with a separate POST request.

Questions:
- Should the registration API allow the submission of a Directory Description to a Directory, in addition to individual Thing Descriptions?
- Should Directory Descriptions be stored directly in a directory such that a Consumer has to access the Things in the directory using its own `things/` endpoint, or should each Thing Description from the directory be added individually, perhaps with a link back to the original directory, e.g. with a "hosts" or "collection" link relation type?
- Related to the above, should directories be nestable (i.e. can you add a directory of directories to a directory?), or kept flat (Thing Descriptions from a Directory are stored individually, each with a link back to one or more other directories it may belong to)?

**Comment by farshidtz** [comment]
This use case may be relevant: https://www.w3.org/TR/wot-usecases/#smart-campus

The registration API currently allows submission of any kind of TD, `discovery:ThingDirectory` is one of those types. Interested consumer would have to query /things endpoints recursively to retrieve nested TDs. I believe this is also what federated SPARQL queries would do:
> A WoT Thing Description Directory MAY implement federation in its SPARQL query API. If implemented, the SPARQL API MUST implement the SPARQL 1.1 Federated Query standard [[sparql11-overview](https://w3c.github.io/wot-discovery/#bib-sparql11-overview)].
https://w3c.github.io/wot-discovery/#search-semantic

You can design it either way. There are pros and cons in each. Here are my thoughts:

- scalability: TDs of devices from buildings in a districts or city will be hard to maintain in a single directory.
- access control: Nested directories can easily implement basic access control using network addresses. Flattened cloud directory would need an advanced mechanism to setup and enforce building-specific and global authorization. 
- ID uniqueness: Not a problem with random IDs, but hard to guarantee and scale in any other way.
- availability: Nested directories can still serve local consumer without internet access. Flattened cloud directories can be replicated and highly available.
- latency/networking costs: Cloud registration can be expensive on frequent writes. Recursive queries can be time consuming on frequent reads.
- maintainability: it is much easier to maintain a single cloud directory.

You can also use nested directories and add an additional proxy directory on the cloud that acts as facade and caches a flattened list of TDs for consumers.

**Comment by benfrancis** [comment]
@farshidtz interesting, thanks.

> The registration API currently allows submission of any kind of TD, `discovery:ThingDirectory` is one of those types. Interested consumer would have to query /things endpoints recursively to retrieve nested TDs.

Is this behaviour explicitly defined anywhere in the specification?

- The specification of the registration API talks about registering a TD (Thing Description). WoT Architecture defines a Thing Description as "Structured data describing a Thing" and doesn't mention directories*
- The specification of the retrieval API talks about retrieving a TD (Thing Description), but doesn't seem to define any special behaviour for a TD with a `@type` of `ThingDirectory` (e.g. recursively fetching /things endpoints)

So I guess your assumption is that a Directory Description would be stored in the directory just like any other TD, and a Consumer which retrieves a Directory Description from the Directory should know that it can fetch the things/ endpoint to retrieve nested TDs?

Presumably then if an implementation of the registration API was instead programmed to traverse the things/ endpoint at the point of registration and add the TDs to the Directory individually (perhaps creating an Enriched TD which includes a Link back to the original directory), that would not comply with the specification? The reason I'm asking is because that's what I'm considering doing for a cloud implementation of a WoT Consumer which is designed to continuously monitor multiple buildings full of devices and would need to store all of the individual TDs in its database to do that.

> You can also use nested directories and add an additional proxy directory on the cloud that acts as facade and caches a flattened list of TDs for consumers.

I think this is pretty close to what I'm describing.

--- 

\* I've noticed that the term "Directory Description" isn't formally defined, and the Directory Service API section doesn't even explicitly mention (as far as I can see) that a directory must expose a Directory Description describing its capabilities. There is an assertion inside section 6 which says "A TD which describes a Thing Description Directory instance MUST use type ThingDirectory" so it's implied, but not quite explicit.

**Comment by farshidtz** [comment]
@benfrancis 

> > The registration API currently allows submission of any kind of TD, discovery:ThingDirectory is one of those types. Interested consumer would have to query /things endpoints recursively to retrieve nested TDs.
> 
> Is this behaviour explicitly defined anywhere in the specification?

I believe @mmccool is going to include that in the architecture section: https://github.com/w3c/wot-discovery/issues/272

>  if an implementation of the registration API was instead programmed to traverse the things/ endpoint at the point of registration and add the TDs to the Directory individually (perhaps creating an Enriched TD which includes a Link back to the original directory), that would not comply with the specification?

It complies as long as you store the submitted TD of the Directory. You can additionally traverse and add the remote TDs without violating the spec.

> I've noticed that the term "Directory Description" isn't formally defined, and the Directory Service API section doesn't even explicitly mention

That's because we replaced Directory Description with ThingDirectory to be consistent with `ThingModel`, `ThingLink`: https://github.com/w3c/wot-discovery/pull/175
There are still uses of it in Introduction Mechanisms which we should clean up.

**Comment by mmccool** [comment]
The section describing Thing Link has a "describedby" relation and one use case mentioned is directory federation.  Basically, if you want to reference one directory from another, embed a Thing Link with the "describedby" relation, and pointing at the other TDD's TD.  It's not necessary to embed the whole TD of the Directory, just the link.

I always thought this was our intended approach.  The problem I see right now is that there are *multiple* ways to do federation, for example, embedding full directory TDs.  I think we need to add some text somewhere saying the Thing Link "describedby" link is the preferred approach.  BTW SPARQL federation still requires the explicit use of the URL of the target service, which has to come from somewhere.  So the idea is you would use the Thing Links to gather all the references to other directories, then embed that in SPARQL queries.  A bit round-about, but I can add this to the "consumer process".  Having the consumer assemble the list of directories it wants to federate puts more work on the consumer but also gives it more control (e.g. to be selective about which other directories to include in a query).

**Comment by farshidtz** [comment]
> The section describing Thing Link has a "describedby" relation and one use case mentioned is directory federation.

I don't see such use case mentioned in the spec. We currently have the following:
https://github.com/w3c/wot-discovery/blob/5d1fb653d831464fd1d4689310d590d84f6e39fc/index.html#L553-L568

The Think Link is mostly useful if the TD of directory is too large, as in the second item above. The consumers have to process Thing Links regardless and that is a separate process. A directory TD can be stored directly in another directory, or hosted elsewhere and referenced using a Thing Link.

Note that directories aren't always self-described, exposing their own TD at a URL, so Thing Link isn't always applicable:
https://github.com/w3c/wot-discovery/blob/5d1fb653d831464fd1d4689310d590d84f6e39fc/index.html#L462-L463

**Comment by benfrancis** [comment]
Related question: Do you think it would be acceptable to modify a TD stored in a Directory to add a link back to the Directory from which it was retrieved? E.g.

```json
{
  "links": [
    {
      "rel": "collection",
      "type": "application/td+json",
      "href": "https://smith.webthings.io"
    }
  ]
}
```

And if so, should that link point to the Directory Description URL, or the /things endpoint?

I wonder whether this is something which should be considered as part of [registration information](https://w3c.github.io/wot-discovery/#exploration-directory-registration-info) in an "enriched TD"?
