### ISSUE TITLE
Needed new assertion for discovery @context

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [w3c/wot-discovery#291]
When a TD is registered into a directory, the Directory adds the registration information. In order for this piece of the TD to be compliant with the JSON-LD 1.1 the directory must always insert the @context URI of the directory (otherwise the registration information is unbounded to an ontology). Currently, this feature is not present in the document (nor in the testing).

**Comment by farshidtz** [comment]
How about when key/values are normalized?

E.g. `https://www.w3.org/2021/wot/discovery#dateCreated` without the context is equivalent to `created` with it.

For `@type`s, we accept also type URIs:

> A TD which describes a Thing Description Directory instance MUST use type ThingDirectory from the discovery context or URI https://www.w3.org/2021/wot/discovery#ThingDirectory.

> A TD which describes a reference to another TD MUST use type ThingLink from the discovery context or URI https://www.w3.org/2021/wot/discovery#ThingLink.

**Comment by AndreaCimminoArriaga** [comment]
The following options are correct:
``` json
{
    "@context": [
        "http://www.w3.org/ns/td",
        "https://w3c.github.io/wot-discovery/context/discovery-context.jsonld"
    ],
    "@type": "DirectoryDescription",
    "title": "Thing Description Directory (TDD)",
    "version": {
        "instance": "1.0.0-alpha"
    },
   "registration": {
        "created": "2021-01-19T17:02:00Z",
        "modified": "2021-01-19T17:02:00Z"
    }
}
```
Alternatively:
``` json
{
    "@context":  "http://www.w3.org/ns/td",
    "@type": "DirectoryDescription",
    "title": "Thing Description Directory (TDD)",
    "version": {
        "instance": "1.0.0-alpha"
    },
   "https://www.w3.org/2021/wot/discovery#hasRegistrationInformation": {
        "https://www.w3.org/2021/wot/discovery#created": "2021-01-19T17:02:00Z",
        "https://www.w3.org/2021/wot/discovery#modified": "2021-01-19T17:02:00Z"
    }
}
```
Or:
``` json
{
    "@context": [
        "http://www.w3.org/ns/td",
      {"tdd":"https://www.w3.org/2021/wot/discovery#"}
    ],
    "@type": "DirectoryDescription",
    "title": "Thing Description Directory (TDD)",
    "version": {
        "instance": "1.0.0-alpha"
    },
  "tdd:hasRegistrationInformation": {
        "tdd:created": "2021-01-19T17:02:00Z",
        "tdd:modified": "2021-01-19T17:02:00Z"
    }
}
```

**Comment by mmccool** [comment]
Discussion:
- We need a temp URL for testing/tooling/validation purposes
- Third style is probably better (IMO) - using explicit tdd prefix
- Base context URL in these examples need to be updated, and there is a namespace already allocated
- We *could* automatically include the tdd context in the td1.1 (similar to how htv is included...), but for td1.0 it will have to be explicitly included (e.g. MAY/SHOULD) - use of tdd prefix is not not mandatory, but RECOMMENDED
- "Expanded" names ok (MAY), but only if base URL is consistent with standard context URL for the tdd

**Comment by mmccool** [comment]
PR #292 should have resolved this issue, closing.
