### ISSUE TITLE
Personal devices and public/private TDDs

### ISSUE THREAD

**Issue by harrisonsean** [w3c/wot-discovery#303]
This issue is part of the PING privacy review [w3cping/privacy-request#83](https://github.com/w3cping/privacy-request/issues/83)

Personal devices, and other devices that may require immutable IDs by law (as mentioned in the TD spec), should only register to public TDDs anonymously, to make fingerprinting and tracking an individual across public TDDs more difficult.

Personal devices should also be disallowed from listing themselves on TDDs with a nosec security policy, with the only exception being for private/local TDDs.

**Comment by mmccool** [comment]
Discussed in WoT Security TF:
- We do not have any objections to making assertions of this nature, they are in alignment to others that we have restricting distribution of PII (and TDs of personal devices are to be considered PII).
- Second one should already be taken care of, as nosec is disallowed on public TDDs for PII, and TDs of personal devices are PII.  But we will check the current wording...

**Comment by mmccool** [comment]
Discussion in Security TF call June 20:
1. Might be other ways to handle this with "salted DIDs" but we need to leave that for 2.0; let's discuss with DID WG.
2. Above seems generally appropriate.  Points of discussion: 
     - Should 1 (making immutable identifiers a property) be a MUST?  Rationale for SHOULD: various situations where immutable identifiers cannot be behind a property, e.g. laws might require.
 3. Probably should add some definitions of tracking to the risk descriptions, using categories here: https://github.com/w3c/wot-thing-description/issues/1497#issuecomment-1129857998, but also tracking of location of personal location, tracking of behaviour.  May be appropriate to point at the GDPR definition of "profiling": [GDPR Article 4.4 "profiling"](https://gdpr-info.eu/art-4-gdpr/)

**Comment by mmccool** [comment]
Made a PR that attempts to address this and related issues: https://github.com/w3c/wot-discovery/pull/353
In security TF, we decided that rather than trying to define tracking on our own, we should depend on an external definition, and the one given by GDPR for "profiling" seemed appropriate.

**Comment by mmccool** [comment]
PR #353 has been merged, along with the related [Thing Description PR 1547](https://github.com/w3c/wot-thing-description/pull/1547).  Has this resolved this issue @harrisonsean ?

**Comment by harrisonsean** [comment]
Apologies for the delay, I've been out for the last few weeks. PR #353 combined with [Thing Description PR 1547](https://github.com/w3c/wot-thing-description/pull/1547) resolves this issue, thanks!

For this particular issue the GDPR "profiling" should work as an external definition.

One last thing to aid in future discussions, it might be worth adding some wording to the spec, particularly near the privacy/security sections, that Things are more analogous to web sites than browsers.

**Comment by mmccool** [comment]
Thanks for the feedback, we'll close this issue.  Note, however, we may have to adjust some of the assertions to make them more testable.   Please follow up on https://github.com/w3c/wot-thing-description/issues/1635.

Point about WoT Things being more server-like is noted, and we probably should say something like that, but saying that raises other problems (not all WoT Things are servers, e.g. MQTT clients).  They are certainly "more like" web servers than browsers.
