### ISSUE TITLE
Self-Description HTTP only?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#314]
Currently the spec has a small parenthetical "e.g." for Self-Description implying CoAP (and possibly other) protocols may be used, but provides assertions only for HTTP.  Currently the explainer draft is written assuming we are only using HTTP.  To keep scope under control, I would like to remove the "(e.g. ...)" in the introduction to this section and normatively define only HTTP (for now; we can consider other protocols in another round).

**Comment by JKRhb** [comment]
I would be fine with restricting the normative statements to HTTP. However, I think it would be unfortunate if the specification said that *only* HTTP could be used for exploration.

Would it be an alternative to say that HTTP is the `RECOMMENDED` solution at the moment, while not explicitly excluding other protocols (or saying that they are `NOT RECOMMENDED`)? Using CoAP for exploring/fetching TDs (if necessary using block-wise transfer) actually works quite well in practice, especially when combined with the CoRE Link Format/CoRE RDs. So dropping support completely would be a bit too drastic, in my opinion.

**Comment by farshidtz** [comment]
If I remember correctly, there were requests in the TF to allow implementation and future addition of CoAP, that's why we ended up with the extensible style in #115. Why not modify the explainer to say HTTP is currently the only normative protocol for self description?
