### ISSUE TITLE
[repository] No link to the spec from the repository

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-discovery#333]
It would be nice if the repository has the "website" information that points to the editor's draft at https://w3c.github.io/wot-discovery/

Examples from arch repo:

![image](https://user-images.githubusercontent.com/20195407/172379487-3026001a-0cde-43d4-a803-cbcec3dcb11a.png)
---
![image](https://user-images.githubusercontent.com/20195407/172379522-4f6f686c-d923-42ec-96b5-ff6626d63247.png)

**Comment by farshidtz** [comment]
It is there:
https://github.com/w3c/wot-discovery/blob/05493204520fa83b84c442bcdd1a26eb36efc4c6/README.md?plain=1#L38

Maybe a consistent template across WoT repos will help in finding such information.

**Comment by egekorkan** [comment]
> Maybe a consistent template across WoT repos will help in finding such information.

I think that was "my" problem. I will work on its unification via the marketing TF.

**Comment by mmccool** [comment]
I assigned Ege to come up with a template :).  BTW it would be useful to have a consistent links to other things too, like github.io renderings of the implementation report, etc.

**Comment by mmccool** [comment]
Added a link to the rendered version as suggested.  That addresses the issue raised in the title of this issue, so I will close this issue... please raise another one for more specific things to fix.  Actually, things like templates, etc. should be discussed in "wot", as they apply to everything.
