### ISSUE TITLE
Improve TD Server for protocols

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#340]
- consider whether to include SHOULD for Size2 option; may be implied by spec anyway (use of block-wise transfers)
- consider whether HEAD in HTTP should be MUST or SHOULD.  Note that Size2 in CoAP is a "SHOULD".
- consider updating Content-Format to allow "application/json" consistent with PR #329

**Comment by mmccool** [comment]
Since this may require changes to normative content (e.g. tweaking MUST to SHOULD or vice-versa) we should resolve by CR transition.

**Comment by mmccool** [comment]
I'm not really the CoAP expert, can someone else comment?   I have assigned some people whose input would be helpful.   It seems to me the current text is ok (although slightly inconsistent) but just want to confirm.

**Comment by JKRhb** [comment]
I think keeping the SHOULD regarding the Size2 option as a recommendation for TD servers would make sense as CoAP servers are not required to support it:

> The Size options are "elective", i.e., a client MUST be prepared for the server to ignore the size estimate request.
> – [RFC 7959, section 4](https://www.rfc-editor.org/rfc/rfc7959#section-4)

A MUST would probably be too strong, but I think advising implementors to provide a size estimate is reasonable.

**Comment by mmccool** [comment]
Discussion (discovery 2022.9.5): not a breaking issue, leave it as is (even if a little inconsistent).
