### ISSUE TITLE
Improve service-http-resp-content-type assertion

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#341]
- The use of "specifically" is a little confusing.  What we want to say is to allow either application/json or application/td+json, but that td+json is more specific (and implies/includes application/json).
- We also need to do the corresponding thing in CoAP, simply allowing two numeric content codes for either application/json or application/td+json

**Comment by farshidtz** [comment]
This working currently appears in three places:

https://github.com/w3c/wot-discovery/blob/898f6071cfd4c24a8658f79867964c71d3d5f49c/index.html#L1057-L1059

https://github.com/w3c/wot-discovery/blob/898f6071cfd4c24a8658f79867964c71d3d5f49c/index.html#L1622-L1624

https://github.com/w3c/wot-discovery/blob/898f6071cfd4c24a8658f79867964c71d3d5f49c/index.html#L1893-L1895
