### ISSUE TITLE
Bullet points in `introduction-dns-sd-txt-record` assertion

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-discovery#342]
Is this a valid assertion? The rendered HTML only highlights the first setence.

https://github.com/w3c/wot-discovery/blob/c7bac4d1f82f4d695bdc964cd429891384502758/index.html#L615-L625

![image](https://user-images.githubusercontent.com/11150423/173383286-bd9b6b5b-b429-4919-a00d-74e6d4454a90.png)

**Comment by mmccool** [comment]
the assertion technically includes the list, but what we're running into here is a limitation of HTML: spans (like paragraphs) are not supposed to include lists, so the HTML parser is probably "repairing" the internal structure and putting a closing tag on the span when it see the list.

We could probably fix this if I update my tooling to take any element with a rfc2119-assertion class as an assertion and then using a div here.   Let me see what I can do...

**Comment by mmccool** [comment]
OK, I updated my script to also capture assertions indicated using div tags, and updated this assertion in particular.  The fix is included in PR #346 so when we merge that this issue will be closed.
