### ISSUE TITLE
Clarification about diff parameter in events

### ISSUE THREAD

**Issue by relu91** [w3c/wot-discovery#354]
Currently, the text says: 
> When diff query parameter is set to true and the event has thing_created type, the server **MAY** return the whole TD object as event data.

Similarly for the thing_updated event: 
> When diff query parameter is set to true and the event has thing_updated type, the server **MAY** inform the client about the updated parts following the JSON Merge Patch [[RFC7396](https://w3c.github.io/wot-discovery/#bib-rfc7396)] format

In my understanding, these two assertions allow an implementer to completely ignore the diff parameter (since the assertion says MAY). However, later on there is an assertion saying:

> When a server which does not support the diff query parameter is requested with such query parameter, it MUST reject the request with 501 (Not Implemented) status.

I probably understand the intention here, nonetheless, the assertions seem to be too benevolent (?). The implementer can:
- Silently ignore the diff parameter (i.e. returning the same payload as if diff is false)
- Or return a 501 

I think we are mixing two styles here (i.e. best-effort approach, sound approach), in my opinion, we should choose one.

**Comment by farshidtz** [comment]
I believe the goal of mandating an error was to make sure the "subscription" isn't started, instead of ignoring the request and later on (next day?) surprising a potentially limited client with payloads that can't fit in its memory.

So the server may support it and has to make it explicit if it doesn't.

**Comment by relu91** [comment]
yeah, that's what I more or less inferred. But, wouldn't be better if the text was clearer? Like instead of having two MAY assertions + a MUST we could have something like:
>A TDD MAY support the `diff` parameter:
>- `thing_created` payload MUST be: etc.
>- `thing_updated` payload MUST be: etc.
>
>When `diff` parameter is not supported the server MUST return 500 etc. 

Obviously, I summarized the text to get the idea.

**Comment by mmccool** [comment]
Discussion:
- Two assertions far apart
- Bringing them together would be hard
- Might be best to add an informative note after the first assertion (@farshidtz will propose a PR with some informative text)

**Comment by farshidtz** [comment]
I took a better look and don't think this is an issue. The assertions follow each other in bullets under the same section (https://w3c.github.io/wot-discovery/#exploration-directory-api-notification -> Events API -> 2nd to 5th bullets.). Adding informative text after each assertion will be repetitive.
