### ISSUE TITLE
Including life time in TDs registration

### ISSUE THREAD

**Issue by AndreaCimminoArriaga** [w3c/wot-discovery#37]
Following the CoAp specification, consider the following feature: when a Thing Description (TD) is registered in a Thing Description Directory (TDD) the client could provide a life time attribute (not necessarily embedded in the TDs) so the TDD knows when a TD is deprecated; after which different actions can be performed. On the one hand the TDD can request a new TD to the target service described, or it can simply remove it.

**Comment by relu91** [comment]
Is this feature similar to TTL? How do they differ? See #18

**Comment by AndreaCimminoArriaga** [comment]
Correct! Many thanks, I did not realise the discussion was already addressed. I will close the issue then.
