### ISSUE TITLE
tm:required --> tm:optional

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-discovery#384]
I just want to point to this discussion since this would also impact the Discovery TM definition:

https://github.com/w3c/wot-thing-description/issues/1594

The discussion is about replacing `tm:required` with `tm:optional` or maybe having none of them at all to keep simplicity. 

I like to hear your opinion. 

In the next TD call on Wednesday I like to have a final decision about this issue.

**Comment by egekorkan** [comment]
@farshidtz What is your take on this and can you join the TD call tomorrow?

**Comment by egekorkan** [comment]
Also, it seems that tm:required is used here as a specification (and validation/requirement). However, the way @thjaeckle is using, is more an OOP approach to model and configure Things. We have a bit of a conflicting use case.

**Comment by farshidtz** [comment]
If we remove it, how can we then specify required interactions?

> @farshidtz What is your take on this and can you join the TD call tomorrow?

We had some discussion at https://github.com/w3c/wot-discovery/pull/253#issuecomment-1004594898 and the next comment. As an alternative, I think it would be nice to have the required field inside the interaction affordance and possibly inside the form. 

I have a conflict but can probably make it to the second half of the call.

**Comment by sebastiankb** [comment]
the basic assumption is, everything is kind of mandatory what is defined in the TM (similar to OOP classes). However, to increase the re-usage  and avoid several variations of TMs we would introduce "tm:optional" (also see here: https://github.com/w3c/wot-thing-description/pull/1640)

**Comment by sebastiankb** [comment]
For the Discovery TM definition, there would be a change from
```
    "tm:required": [
        "#/properties/things"
    ],
```
to
```
    "tm:optional": [
        "#/actions/createThing",
        "#/actions/createAnonymousThing",
        "#/actions/retrieveThing",
        "#/actions/updateThing",
        "#/actions/partiallyUpdateThing",
        "#/actions/deleteThing",
        ...
    ],
```

**Comment by farshidtz** [comment]
Thanks @sebastiankb. I think it is fine for discovery as long as we have a way of specifying what is or isn't required. Making everything required by default and using `tm:optional` as you suggested works.

**Comment by sebastiankb** [comment]
from today's TD call:
- decided to go this direction with "tm:optional"
- @mmccool will setup an PR to change this in the Discovery  spec

**Comment by mmccool** [comment]
Duplicate, see issue #388, @farshidtz will resolve.
