### ISSUE TITLE
Use Case due diligence

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-discovery#439]
An initial assessment was done earlier this year.

The task is to complete the assessment for architecture at:

https://github.com/w3c/wot-usecases/blob/main/USE-CASES/coverage.csv

See also: https://github.com/w3c/wot-usecases/blob/main/USE-CASES/coverage.md

**Comment by mmccool** [comment]
Coverage table has been filled in for discovery.  More work to do to extract requirements for Discovery 2.0, but issue as stated (fill in coverage table) completed.
