### ISSUE TITLE
TDD Thing Model is missing `contentType` in `response` objects

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-discovery#465]
Experimenting with discovery from TDDs, I noticed that a TDD implementation that adheres to the currently defined Thing Model for the API specification ends up generating a Thing Description that is not valid according to the TD specification. That is because a form like the following does not define a `contentType` for its `response` member, causing an instantiated TD to be invalid if no `contentType` is explicitly added by the TDD:

```js
{
    "href": "/things/{id}",
    "htv:methodName": "PUT",
    "contentType": "application/td+json",
    "response": {
        "description": "Success response",
        "htv:statusCodeValue": 201
        // No contentType defined!
    },
    "additionalResponses": [
        {
            ...
        }
    ]
}
```

As also discussed in https://github.com/w3c/wot-thing-description/pull/1776, having no `contentType` seems reasonable to me here – however, if a discovery validates a TDD's Thing Description, then it is rejected in its current form.

Would it be a possible workaround to add `application/octet-stream` for cases like these? Or is there maybe a better alternative?

**Comment by mmccool** [comment]
Can't add an assertion, at most can add an informative statement.  Worst case, we mention the above workaround using application/octet-stream.

**Comment by farshidtz** [comment]
A content type should not be needed when there is no content (no HTTP body). Enforcing that on directories would be really strange.

See also:
- https://stackoverflow.com/questions/29784398/should-content-type-header-be-present-when-the-message-body-is-empty
- https://stackoverflow.com/questions/21029351/what-content-type-should-a-204-no-response-use
- https://stackoverflow.com/questions/22326994/is-there-a-standard-null-mime-type a comment suggests using `application/x-empty`.

I suggest we wait and hope that `contentType` becomes optional in an upcoming TD spec patch.
