### ISSUE TITLE
Removing the RFC 9175 assertion?

### ISSUE THREAD

**Issue by JKRhb** [w3c/wot-discovery#466]
One assertion in the "Amplification and Distributed Denial of Service" section currently reads as follows:

> If support for multicast is required, in the case of CoAP, the recommendations made in [[RFC9175](https://www.w3.org/TR/wot-discovery/#bib-rfc9175)] SHOULD be applied.

Revisiting this assertion, I noticed that this wording does not make that much sense, since RFC 9175 only contains an explicit recommendation for multicast in the case of OSCORE-protected group communication. Furthermore, it already contains this assertion, making the assertion in the Discovery specification a bit redundant:

> A CoAP server SHOULD mitigate potential amplification attacks by responding to unauthenticated clients with 4.01 (Unauthorized) including an Echo option, as described in item 3 in [Section 2.4](https://datatracker.ietf.org/doc/html/rfc9175#echo-app) of RFC 9175.

Therefore, I was wondering if the reference to RFC 9175 should be dropped completely or reworded to an informative statement, possibly referring to [`draft-irtf-t2trg-amplification-attacks`](https://datatracker.ietf.org/doc/html/draft-irtf-t2trg-amplification-attacks) (where possible amplification attacks using CoAP and multicast are illustrated) instead.

I suppose this issue could also be discussed in the next meeting of the security TF.

**Comment by mmccool** [comment]
Resolution: convert this at-risk assertion to the following informative content:
```
If support for multicast is required, in the case of CoAP, the recommendations made in [[t2trg-amplification-attacks](https://datatracker.ietf.org/doc/html/draft-irtf-t2trg-amplification-attacks)] are relevant.
```
@JKRhb will prepare a PR.
