### ISSUE TITLE
Create and Publish an Ontology File for DID Vocabulary

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#509]
To finalize the DID introduction method, we have to create an ontology file defining the terms to be used in the DID document AND make it available so it can be fetched from the context URL in the specification.

* [x] Create ontology file (Andrea) to define WotThing and WotDirectory (see PR below)
* [x] Make it available at URL given in Specification (McCool/Kaz) - https://www.w3.org/2022/wot/discovery-did

Related Issues:
* https://github.com/w3c/wot-discovery/issues/467
* https://github.com/w3c/wot-discovery/issues/402

Related PRs:
* https://github.com/w3c/did-spec-registries/pull/486/files (will be reopened)

**Comment by AndreaCimminoArriaga** [comment]
The discovery ontology has been extended in this PR #511 with the types WotDirectory and WotThing. Then, PR #512 creates a new different context file for DID introduction.

**Comment by mmccool** [comment]
PR #516 creates a location for the "frozen" resources files to go into.
