### ISSUE TITLE
Publish JSON Schema for TDD at stable URL

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#518]
We discussed publishing the ontology and content files at an official location but it would probably also be a good idea to publish the validation files (e.g. the JSON Schema files for TDDs) somewhere consistent and stable, i.e. not just in github.

**Comment by egekorkan** [comment]
For TD, we also publish it. See https://github.com/w3c/wot-thing-description/tree/main/publication/ver11/7-rec/validation and https://w3c.github.io/wot-thing-description/#json-schema-for-validation

**Comment by mmccool** [comment]
This will be resolved once we publish the associated resources (see https://github.com/w3c/wot-resources/tree/main/discovery/v1 )

**Comment by mmccool** [comment]
Published - see [wot-resources](https://github.com/w3c/wot-resources/tree/main/discovery/v1)
