### ISSUE TITLE
Reach out to JSONPath community

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#56]
1. Define "JSONPath community" as Stefan Goessner + set of implementers
    * https://goessner.net/articles/JsonPath/ 
    * https://github.com/json-path/JsonPath 
    * https://jsonpath.com
2. Reach out to them to determine plans for standardization
3. Decide how we will deal with this in our spec (PLH input needed)

**Comment by farshidtz** [comment]
See https://github.com/cburgmer/json-path-comparison/issues/70

**Comment by mmccool** [comment]
Add to above: collaborate with IETF groups working on this (contact: Carsten Bormann).

**Comment by mmccool** [comment]
I probably would be good to organize a joint call with T2TRG on this, but it may have to wait until after TPAC as the agenda for TPAC is getting pretty full.

**Comment by k-toumura** [comment]
IETF jsonpath WG has been formed. 
https://mailarchive.ietf.org/arch/msg/ietf-announce/gETCDPfifXG6y4iq3CrgD-sH3-c/
https://datatracker.ietf.org/group/jsonpath/about/

**Comment by farshidtz** [comment]
@mmccool Should we close this and continue on https://github.com/w3c/wot-discovery/issues/129?
