### ISSUE TITLE
Index prior work

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#6]
add links to prior.md pointing to previous work

**Comment by vcharpenay** [comment]
See 3eced81 (for Thing Directory-related work).

**Comment by k-toumura** [comment]
Issue #5 is related to this issue (Fujitsu's prior Directory work, and future Discovery work).

**Comment by mmccool** [comment]
let's consider this done for now...  people who are aware of prior work should just submit PRs, and eventually this should go into an explainer doc
