### ISSUE TITLE
How to deal with JSON-LD fragments in query responses

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#63]
Exists for XPath, JSONPath, and SPARQL.

**Comment by farshidtz** [comment]
According to the current draft spec, the server is expected to set Content-Type as `application/json` instead of `application/td+json` whenever the response is or might be TD fragments.

**Comment by mmccool** [comment]
Resolution: Since we closed https://github.com/w3c/wot-discovery/issues/21, can close this issue for the same reasons.
