### ISSUE TITLE
Feedback to Editor's Draft 29 September 2020

### ISSUE THREAD

**Issue by wiresio** [w3c/wot-discovery#77]
1. 6.2.2. - TD has "events" twice (Update: FIXED)
2. We should mention that an openAPI / Swagger can be easily created out of this TD.
3. The MUST/SHALL/MAY of 6.2.2.4 are almost overread with the later MUSTs for all 6.2.2.4.{1,2,3}

**Comment by farshidtz** [comment]
> The MUST/SHALL/MAY of 6.2.2.4 are almost overread with the later MUSTs for all 6.2.2.4.{1,2,3}
The idea was to say XPath and SPARQL are recommended and optional respectively, but if provided, they must follow the spec. I agree the current text doesn't make that clear.

**Comment by mmccool** [comment]
Meeting 2020.10.12:
- Farshid resolved 1 (merged)
- Farshid to resolve 2 for the FPWD by adding an editors' note (and add an issue for a final resolution)
- Farshid to resolve 3 by proposing improved text

**Comment by farshidtz** [comment]
@wiresio Thank again for the feedback. I've addressed all your points. Do you agree on closing this?

**Comment by wiresio** [comment]
@farshidtz - thanks for the changes!  

One little proposal wrt "6.2.2.4.3 Semantic search: SPARQL"
"The optional SPARQL search API MUST allow" ...    
->   
"The support for SPARQL Search API is optional. If implemented the SPARQL query API MUST allow" ...

That's it, then we can close.
