### ISSUE TITLE
"Thing description" for Directory should be a "Thing Model"

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#86]
The TD defined for a Directory service should really be a Thing Model.  We should also "template" the "base" parameter (or omit it, and say it needs to be added when the Thing Model is instantiated).

Since we are talking about a class of things, we should have a Thing Model.  However, the definition of Thing Model needs to be updated to allow specifying security scheme templates, form templates (including URL templates giving https), etc.

**Comment by farshidtz** [comment]
Is that the [WoT Binding Template](https://w3c.github.io/wot-binding-templates/)?
When I search for WoT Thing Model, I only find content referring to https://www.w3.org/Submission/wot-model/

**Comment by mmccool** [comment]
Thing Models used to be called "Thing Description Templates" which were basically Thing Descriptions that omitted instance-specific information.  But the TD 1.1 spec is attempting to make this a little clearer and allow URL templates (for instance) rather than just omitting hrefs.  I think all was need to do is use the following:

  "base": "https://{DIRECTORY}"

or the like.  I'd rather use a template like this rather than omitting the base so it's clear that it needs to be filled in.

**Comment by egekorkan** [comment]
@farshidtz there is work going on here: https://w3c.github.io/wot-thing-description/#thing-model

@mmccool: I completely agree :)

**Comment by farshidtz** [comment]
@egekorkan thanks for the link.
@mmccool it is clear now. But I think it needs more changes to become a Thing Model:

1. `base` must be replaced with placeholder, as @mmccool mentioned.

https://github.com/w3c/wot-discovery/blob/fad66ff0ff46ba72ac73420f65d8ff792103ec45/directory.td.json#L51

2. `@type` must be ThingModel
> Thing Model definitions MUST use the keyword @type at top level and a value of type string or array that equals or respectively contains ThingModel

https://github.com/w3c/wot-discovery/blob/fad66ff0ff46ba72ac73420f65d8ff792103ec45/directory.td.json#L3

3. `securityDefinitions` should be completely omitted? We don't know what schemes the instances will use.

https://github.com/w3c/wot-discovery/blob/fad66ff0ff46ba72ac73420f65d8ff792103ec45/directory.td.json#L8-L49

---

My suggestion is to keep the Thing Description as is: [An example TD](https://w3c.github.io/wot-discovery/#directory-thing-description).

**Comment by relu91** [comment]
The Thing Model is still under discussion, but I don't see any problem in leaving SecurityDenifitions as long as we substitute specific URLs with URL templates.

**Comment by zolkis** [comment]
When consumed, IMHO it should be a TD, or instance-specific information needs to be shared out of band, right?
When defined, it could be a TM, until exposed (likewise, in other use cases as well).

**Comment by mmccool** [comment]
@benfrancis can you clarify your downvote, please?

**Comment by benfrancis** [comment]
@mmccool Thank you for the clarification, I was indeed confused by your original description. From scanning the F2F meeting minutes I suspected I may have misunderstood that context, but hadn't had chance to catch up yet, so apologies for the misunderstanding. I've removed the downvote.

I just wanted to make sure that a physical device providing a directory service (i.e. a gateway) can use a single Thing Description to describe its directory service in addition to other properties, actions and events representing its own physical affordances.

I'm still not keen on the general idea of inventing a new JSON templating language (Thing Description Templates/Thing Models) just for WoT Thing Descriptions, but I don't have a particular objection to using it as a mechanism to describe the directory API in the WoT Discovery specification itself.

**Comment by mmccool** [comment]
To clarify, a TDD instance would return a TD, not a TM.  The TM is just a template that constrains the TD used by TDDs.  We need to take our current "example TD" and turn it into a TM as a starting point.  If we're not sure about something (e.g. should we have securityDefinitions) we can just omit them for now, then argue about whether we should add them later.  I think we should keep the current TD as an example since it DOES show some of these blanks filled in (eg. security).

**Comment by mmccool** [comment]
Note we can leave the "scopes" in the forms even in a TM that does not define a securityScheme.  They are orthogonal to the use of OAuth, and having consistent scopes across all TDDs is a fine thing.

**Comment by mmccool** [comment]
Note the data schema for query responses needs some consideration.  For instance, the return data schema for XPath 3.1 may not include objects since it is converted from XML.  See https://github.com/w3c/wot-discovery/pull/248.  Also, JSONPath and XPath APIs are only "suggestions" (informative) and may change.  If the TM is normative, then including them is troublesome, but perhaps we can mark them as informative (in the TM, and in the introduction).

**Comment by farshidtz** [comment]
@mmccool 
> JSONPath and XPath APIs are only "suggestions" (informative) and may change. If the TM is normative, then including them is troublesome, but perhaps we can mark them as informative (in the TM, and in the introduction).

I don't like what I'm about to suggest due to its complexity, but I think that is technically the right way to do it:

Move JSONPath and XPath to another TM kept in an informative section which extends the normative one. TM extension and import: https://w3c.github.io/wot-thing-description/#thing-model-extension-import

**Comment by mmccool** [comment]
XPath is not going to change, nor should SPARQL.  These should be optional but normative.
JSONPath is, however, subject to change, and the IETF spec is missing some key features like substring matching, and that’s an issue.
We *could* just leave it out.
Michael McCool

From: Farshid Tavakolizadeh ***@***.***>
Date: Friday, February 18, 2022 at 9:01 AM
To: w3c/wot-discovery ***@***.***>
Cc: Mccool, Michael ***@***.***>, Mention ***@***.***>
Subject: Re: [w3c/wot-discovery] "Thing description" for Directory should be a "Thing Model" (#86)

@mmccool<https://github.com/mmccool>

JSONPath and XPath APIs are only "suggestions" (informative) and may change. If the TM is normative, then including them is troublesome, but perhaps we can mark them as informative (in the TM, and in the introduction).

I don't like what I'm about to suggest due to its complexity, but I think that is technically the right way to do it:

Move JSONPath and XPath to another TM kept in an informative section which extends the normative one. TM extension and import: https://w3c.github.io/wot-thing-description/#thing-model-extension-import

**Comment by mmccool** [comment]
There is now a TM in the spec so I am closing this issue.
