### ISSUE TITLE
Richer diff model for update notifications

### ISSUE THREAD

**Issue by farshidtz** [w3c/wot-discovery#87]
At the time of writing, the notification API spec provides the optional feature of including a diff on update events. The diff is a Partial TD JSON object including the changed elements. For create events, the whole new TD is included.

https://w3c.github.io/wot-discovery/#exploration-directory-api-notification

As raised by @mmccool, this can't carry information about partial deletions. Moreover, a client won't be able to distinguish between added and updated elements.

**Comment by farshidtz** [comment]
I think we can extend to model to include something like:
```json
{
  "td_id": "TD identifier",
  "added": { Partial TD with added elements },
  "updated": { Partial TD with updated elements },
  "deleted": { Partial TD with deleted elements } 
```
The same model can be used for all three types of events, not just for updates.

**Comment by relu91** [comment]
I think that the updated field could be expressed with just `added` and `removed`. For example, updating the TD title:
```json
{
  "td_id": "TD identifier",
  "added": { 
     "title": "New Title"
   },
  "deleted": { 
      "title":"Old Title"
  }
} 
```
It feels cleaner to me. What do you think?

**Comment by farshidtz** [comment]
True, it is cleaner. But I feel like our proposal is making it better for humans rather than machines. 

Thinking about the original model again, the 'updated_td' event:
```json
{
  "td_id": "TD identifier",
  "td_updates": { 
     // partial TD
   }
} 
```

This could actually present removed fields too. E.g. when title is removed:
```json
{
  "td_id": "TD identifier",
  "td_updates": { 
     "title": null
   }
} 
```

The consumer can simply patch its original copy with this `td_updates` object to have the latest TD. This object is exactly what a producer would submit to a directory to remove the title using an HTTP PATCH request.

Why is it necessary for an application to receive "the removed information" in an event?

**Comment by relu91** [comment]
I see what you mean. In fact, I don't have a strong opinion about using my proposal either. It makes some use case easier (like what was the previous value? no need to check on my cached instance) but it makes other harder (i.e. now if I have to update my local cache of the TD I have first remove and add -> not fancy). 

Anyway, I have a question:
```json

{
 "td_id": "TD identifier",
 "td_updates": {
    "title": null
  }
}

```

shouldn't be `title: undefined`?

**Comment by farshidtz** [comment]
> ```json
> 
> {
>  "td_id": "TD identifier",
>  "td_updates": {
>     "title": null
>   }
> }
> 
> ```
> 
> shouldn't be `title: undefined`? 

`undefined` is not a JSON value. I think in this case, we can use `null` to communicate that the value is unset or that the field is omitted.

Helpful info: https://stackoverflow.com/a/21122019
