### ISSUE TITLE
Should security be mandatory on directories for WoT Discovery?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#96]
- Should security be mandatory on directories?
- If so, what scheme?
- What security is appropriate for what contexts?
Note that since queries can be expensive, we may want to control access even in "open" contexts to avoid denial-of-service attacks.

This is also a use case to allow security schemes in Thing Models (eg if we use a TM to define the API for a directory, but also want to specify the security scheme in that TM)

**Comment by benfrancis** [comment]
As with any other Thing Description I can imagine scenarios where there might be a public directory with no authentication, or a read-only directory which requires authentication to write. So no, I don't think security metadata should be mandatory for directories (or Thing Descriptions in general for that matter).

**Comment by mmccool** [comment]
I agree in principle that there are contexts where "open" directory services make sense, but there are some semi-technical issues with "open" directories:
1. If queries are expensive, or if a query can return a lot of data (eg return all TDs) then it can be a DDoS target.   This can be mitigated in various ways, e.g. by rate-limiting queries, or have a time limit, from different sources.   This could be discussed under "Security Considerations".
2. There might be use cases for directories where queries require authentication, but fetching a TD by ID or listing all TDs (paginated) does not.   This might be a compromise.
3. An OAuth-based mechanism for security could still be "open" in the sense that accounts are free, but then there (might...) be a tracking issue (a privacy concern).

There are contexts where we MUST have security, i.e. if PII is present or can be inferred.  In which case, we probably do want to indicate a best practice.

**Comment by mmccool** [comment]
Then there's https://github.com/w3c/wot-discovery/issues/135 
As I propose in my response there, at the very least we should limit security schemes for directories to those that can be identified from the protocol itself so the initial fetch of the directory's TD can be done (it could then specify other schemes).
One VERY simple solution is to always use nosec for the fetch of a directory's TD, since it should not have any private information, it just says how to use the rest of the directory's resources (and what authentication is needed to access them...), which can be different.

**Comment by benfrancis** [comment]
I suggest that security metadata should be mandatory at the top level of a TDD's Thing Description as it is for all other Thing Descriptions, but that `nosec` is an acceptable value.

**Comment by mmccool** [comment]
We were reviewing the security assertions just today (22.8) and were discussing the MUST assertion disallowing nosec in the case of PII, and wondering if this conflicted with other things (e.g. there is another assertion saying you MAY omit access controls in a segmented network).   These seem to be a bit in conflict, and also (potentially) in conflict with weaker assertions in the TD spec.  Need to review, and quickly...

**Comment by mmccool** [comment]
I can't find that issue any more, so it seems we have fixed it and I forgot to close this issue.  At any point, we have discussed this at length, have a general policy for default security that applies also to directories, and the MUST issue noted above is no longer in the spec. 

Discussion (discovery call 2022.9.5): close this issue.
